### ISSUE TITLE
Migration is not working as expected

### ISSUE THREAD

**Issue by mkurczewski** [sindresorhus/electron-store#142]
Hi. I'm struggling with the following problem... I have a store for app's settings

```TSX
import Store from "electron-store"
import { app } from "electron"
import { name, version } from "../../../package.json"
import settingsSchema from "App/main/store/settings.schema"

const settingsStore = new Store({
  name: "settings",
  cwd: `${app.getPath("appData")}/${name}`,
  schema: settingsSchema,
  clearInvalidConfig: true,
  projectVersion: version,
  migrations: {
    ">=0.9.2": (store) => { // The same as in package.json
      store.set("language", "en-US")
    },
  },
})
```

but the migration is not working. The previous `language` key was 
```JSON
"language": {
  "name": "English",
  "tag": "en-US",
  "shortTag": "en"
}
```
so I'm getting
```
Error: Config schema violation: `language` should be string
    at ElectronStore._validate (webpack:///./node_modules/conf/dist/source/index.js?:346:15)
    at ElectronStore.get store [as store] (webpack:///./node_modules/conf/dist/source/index.js?:265:18)
    at new Conf (webpack:///./node_modules/conf/dist/source/index.js?:124:32)
    at new ElectronStore (webpack:///./node_modules/electron-store/index.js?:23:3)
    at eval (webpack:///./src/main/store/settings.ts?:20:23)
```
which is true - it should be a string now as I changed the schema too. But this brokes the app and no migration is performed at all.

Settings schema is as follows
```TSX
language: {
  type: "string",
  default: "en-US,
},
```

How should I migrate it to avoid errors?

The only way to make it work is to update `language` key in `settings.json` manually which is far from fine, even before app's release. And what then? Should I tell all the users to update their `settings.json` files manually or create some complex scripts that will make the migration in a right way?

**Comment by sindresorhus** [comment]
Turns out the migration feature (added in https://github.com/sindresorhus/electron-store/commit/4101982b64276e27bda1545f384deff7673b122f) never worked properly... Should be fixed by https://github.com/sindresorhus/electron-store/commit/dced818be88524d804812d4ccc2e8f9b708c10c5 though.

**Comment by Lovinity** [comment]
Unfortunately, the problem still exists in version 6.0.1 (either that, or there is another problem).

I am attempting to upgrade the app from 8.0.0-alpha.17 to 8.0.0-alpha.18. Alpha.18 has schema changes which forbid additional properties and remove previously-used properties in alpha.17. Thus, the migration >=8.0.0-alpha.18 defines to have those unused keys deleted.

I expect that migration script to get called prior to the config being loaded, thereby removing the old keys, loading in the config correctly, and updating the internal migration version.

Instead, the migration script never gets called and instead I get an error about a schema violation.

**Comment by Lovinity** [comment]
Additional problem/note that is potentially related to this: When there is a schema validation error in the config and clearInvalidConfig is true, electron-store does not clear the invalid config. I'm not sure if this is by design.
