### ISSUE TITLE
version 7 is slow in initializing 

### ISSUE THREAD

**Issue by pejman1** [sindresorhus/electron-store#183]
I have installed version 7.0.3 but it expands time of application launching more than 5 sec in comparison to the version 6.0.1

Electron version 12.0.2
Windows 10

**Comment by sindresorhus** [comment]
Are you really sure it's this package doing it? And if so, try to use DevTools to measure what exact function is slowing it down. I cannot really do anything based on the current information.

**Comment by pejman1** [comment]
> Are you really sure it's this package doing it? And if so, try to use DevTools to measure what exact function is slowing it down. I cannot really do anything based on the current information.

I am sure . if I downgrade to version 6.0.1 the issue will solve

**Comment by andresavic** [comment]
I never used electron-store before, but I expierence the same issue.  My application startup time is with version 7.0.3 about 6ish seconds.

**Comment by sjlei** [comment]
I have this problem too.
There are problems with versions above `6.0.1`

**Comment by sjlei** [comment]
Chrome: 89.0.4389.114
Electron: 12.0.4
NodeJS: 14.16.0

**Comment by sindresorhus** [comment]
Resolved: https://github.com/sindresorhus/electron-store/issues/188

**Comment by pejman1** [comment]
> Resolved: #188

I don't use store in main process and it does not solve the issue for me
